services:
  - type: web 
    plan: free
    name: achievementtravels
    runtime: node
    repo: https://github.com/achievementtravels/achievementtravels.git
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: ZOHO_EMAIL
        sync: false
      - key: ZOHO_RECEIVE_EMAIL
        sync: false
      - key: ZOHO_PASS
        sync: false